channels:
  - conda-forge
dependencies:
  - python=3.11.14
  - r-base=4.5.2
  - ipykernel
  - salib
  - zlib
  - qpdf
  - r-essentials
  - r-devtools
  - r-remotes
  - r-tidyverse
  - r-xslt
  - r-ggrepel
  - r-lhs
  - r-gridextra
  - r-doparallel
  - r-xml
  - r-xml2
  - r-rsqlite
  - r-plogr
  - r-pak
  - r-nloptr
  - r-tictoc
  - r-lme4
  - r-future.apply
  - r-future
  - r-here
  - r-png
  - r-reticulate
  - r-rcpptoml
  - r-rjson
  - r-stringr
  - r-ggh4x
  - r-pbapply
  - r-rcppparallel
  - r-clue
  - r-covr
